project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "NYC Crime Stats"
  author:
    - Austin Schaefer (as7082)
    - Andy Kim (dk3315)
  repo-url: https://github.com/schaefer30037/NYCCrimeStats
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


